import { ThemeProvider } from "@/components/theme-provider";
import "./globals.css";
import Header from "@/components/header/header";
import Footer from "@/components/footer/footer";

export const metadata = {
  title: "Saiful Alom",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {

  return (
    <html lang="en" className="dark" suppressHydrationWarning>
      <body>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <Header/>
          <div className="py-16">
            {children}
          </div>
          <Footer/>
        </ThemeProvider>
      </body>
    </html>
  );
}
